#!/bin/bash
#Initial wifi interface configuration
ip link set up dev $1
###########Start DHCP, comment out / add relevant section##########
#Thanks to Panji
#Doesn't try to run dhcpd when already running
if [ "$(ps -e | grep dhcpd)" == "" ]; then
ip addr add 10.0.0.1/24 dev $1
dhcpd -q $1
fi
###########
#Enable NAT
iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
iptables -A FORWARD -i $1 -j ACCEPT

#Thanks to lorenzo
#Uncomment the line below if facing problems while sharing PPPoE, see lorenzo's comment for more details
#iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

sysctl -q -w net.ipv4.ip_forward=1
#start hostapd
hostapd -B $3 >/dev/null 2>&1
